#!/usr/bin/env bash
# bash script that installs nginx web server 

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
service nginx start
