#!/usr/bin/env bash
# bash script diaplaying "to infinity and beyond" indefinitely
# print "I am invincible!!!" when SIGTERM signal is received

trap "echo 'I am invincible!!!'" SIGTERM
while true; do
      echo "To infinity and beyond"
      sleep 2
done
