#!/usr/bin/env bash
# This script is displaying "Best School" for 1-10
# except 4 - bad luck and 8- good luck

i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif  [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
