#!/usr/bin/env bash
# This script is displaying the time for 12 hr 59m

h=0

while [ $h -lt 13 ]; do
	echo -n "Hour: "
	echo $h
	m=1
	while [ $m -lt 60 ]; do
		echo $m
		m=$((m+1))
	done
	h=$((h+1))
done		
