#!/usr/bin/env bash
# install the ufw firewall and setup a few config rules

sudo apt install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
